// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const changePasswordAndUsername = `-- name: ChangePasswordAndUsername :one
UPDATE users SET username = $2,
hashed_password = $3
WHERE id = $1
RETURNING id, created_at, updated_at, username, hashed_password
`

type ChangePasswordAndUsernameParams struct {
	ID             uuid.UUID
	Username       string
	HashedPassword string
}

func (q *Queries) ChangePasswordAndUsername(ctx context.Context, arg ChangePasswordAndUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, changePasswordAndUsername, arg.ID, arg.Username, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.HashedPassword,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, username, hashed_password)
VALUES (gen_random_uuid(), NOW(), NOW(), $1, $2)
RETURNING id, created_at, updated_at, username, hashed_password
`

type CreateUserParams struct {
	Username       string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.HashedPassword,
	)
	return i, err
}

const getUserFromUsername = `-- name: GetUserFromUsername :one
SELECT id, created_at, updated_at, username, hashed_password FROM users
WHERE username = $1
`

func (q *Queries) GetUserFromUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.HashedPassword,
	)
	return i, err
}

const getUsernameFromID = `-- name: GetUsernameFromID :one
SELECT username FROM users
WHERE id = $1
`

func (q *Queries) GetUsernameFromID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUsernameFromID, id)
	var username string
	err := row.Scan(&username)
	return username, err
}
